### ISSUE TITLE
Timestamp is in the future and the app fails to run

### ISSUE THREAD

**Issue by bsf29** [israndy/TesSense#7]
Occasionally I get the following error and have to retry later in the day. 

Traceback (most recent call last):
  File "/data/projects/TesSense-new/TesSenseTes.py", line 543, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/data/projects/TesSense-new/TesSenseTes.py", line 538, in main
    await asyncio.gather(*tasks)
  File "/data/projects/TesSense-new/TesSenseTes.py", line 248, in TesSense
    print(' last seen ' + vehicles[CAR].last_seen(), end='')
  File "/home/brypi/.local/lib/python3.9/site-packages/teslapy/__init__.py", line 626, in last_seen
    raise ValueError('Timestamp is in the future')

**Comment by israndy** [comment]
Try it now and let me know

**Comment by bsf29** [comment]
Thanks Randy.
I think it's fixed, but I don't always get the future time error.  I'll let you know if I see any problems.  

New Feature request(s).....We have 2 Tesla and I would like to track the power separate in Sense.  I can do a little in Python and created 2 copies of your py customized for each car.  Specifically having different mutable plug mac addresses for each car.  Would it be possible to have you update the code to support this in a single source file?  I don't charge both cars at the same time over solar so I'm not looking to attempt to split the available power.  Since the plug is created before you query Tesla, this is probably a huge ask😟  I don't know if you can create multiple plugs and associate them to each car once you connect to Tesla.  
Occasionally I do charge the cars at night from the grid.  I have forgotten to stop TesSense and it stopped my charging since there was no extra solar.  It would be nice to have TesSense just track and update Sense.  Defaulting from sunset to sunrise, but being able to specify "tracking only time" range would be cool.  
Our electric co-op doesn't do Time Of Use and we have a battery on our solar system, so I've had to tweak your code to have grid_reserve and minimize pulling from our battery.  This also caused me to check/update every 60 seconds being cautious of your comment that Sense can't update <30 seconds.  I also decrease the charge more aggressively (3*grid_reserve) when there isn't enough excess solar.  Basically I'm being proactive that the slight cloud could move and really impact our solar production.  I also have a max_rate_increase so a sudden spike in solar production (when the sun comes out from behind clouds), doesn't cause the car to have a large increase when there is a good chance the sun will go back behind the clouds and now I'm pulling from battery again.  

THANKS AGAIN for fixing the Future Time issue.  
    On Friday, December 8, 2023, 09:24:31 AM EST, israndy ***@***.***> wrote:  
 
 


Closed #7 as completed.
